projects/financial/src/main/java/com/opengamma/batch/domain/RiskRun.java
/**
 * Copyright (C) 2009 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.batch.domain;

import static com.opengamma.lambdava.streams.Lambdava.functional;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBean;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.threeten.bp.Instant;

import com.google.common.collect.Sets;
import com.opengamma.batch.BatchMaster;
import com.opengamma.batch.SnapshotMode;
import com.opengamma.engine.ComputationTargetResolver;
import com.opengamma.engine.view.cycle.ViewCycleMetadata;
import com.opengamma.id.ObjectId;
import com.opengamma.id.ObjectIdentifiable;
import com.opengamma.id.UniqueId;
import com.opengamma.id.VersionCorrection;
import com.opengamma.lambdava.functions.Function1;

/**
 * Bean to hold data about a risk run.
 */
@BeanDefinition
public class RiskRun extends DirectBean implements ObjectIdentifiable {

  @PropertyDefinition
  private long _id;

  @PropertyDefinition
  private MarketData _marketData;

  @PropertyDefinition
  private Instant _createInstant;

  @PropertyDefinition
  private Instant _startInstant;

  @PropertyDefinition
  private Instant _endInstant;

  @PropertyDefinition
  private Instant _valuationTime;

  @PropertyDefinition
  private int _numRestarts;

  @PropertyDefinition
  private Set<CalculationConfiguration> _calculationConfigurations = new HashSet<>();

  @PropertyDefinition
  private Set<RiskRunProperty> _properties = new HashSet<>();

  @PropertyDefinition
  private boolean _complete;

  @PropertyDefinition
  private VersionCorrection _versionCorrection;

  @PropertyDefinition
  private String _viewDefinitionUidScheme;

  @PropertyDefinition
  private String _viewDefinitionUidValue;

  @PropertyDefinition
  private String _viewDefinitionUidVersion;

  @PropertyDefinition
  private SnapshotMode _snapshotMode;

  @PropertyDefinition
  private ComputationTargetResolver _computationTargetResolver;

  @PropertyDefinition
  private String _name;

  /**
   * Gets the viewDefinitionUid.
   * @return the value of the property
   */
  public UniqueId getViewDefinitionUid() {
    return UniqueId.of(getViewDefinitionUidScheme(), getViewDefinitionUidValue(), getViewDefinitionUidVersion());
  }

  /**
   * Sets the viewDefinitionUid.
   * @param viewDefinitionUid  the new value of the property
   */
  public void setViewDefinitionUid(final UniqueId viewDefinitionUid) {
    setViewDefinitionUidScheme(viewDefinitionUid.getScheme());
    setViewDefinitionUidValue(viewDefinitionUid.getValue());
    setViewDefinitionUidVersion(viewDefinitionUid.getVersion());
  }

  @Override
  public ObjectId getObjectId() {
    return ObjectId.of(BatchMaster.BATCH_IDENTIFIER_SCHEME, Long.toString(getId()));
  }

  public RiskRun() {
  }

  public RiskRun(final MarketData marketData, final Instant createInstant, final Instant valuationTime, final int numRestarts,
      final Set<CalculationConfiguration> calculationConfigurations, final Set<RiskRunProperty> properties, final boolean complete,
      final VersionCorrection versionCorrection, final UniqueId viewDefinitionUid, final String name) {
    this._marketData = marketData;
    this._createInstant = createInstant;
    this._valuationTime = valuationTime;
    this._numRestarts = numRestarts;
    this._calculationConfigurations = calculationConfigurations;
    this._properties = properties;
    this._complete = complete;
    this._versionCorrection = versionCorrection;
    this._name = name;
    setViewDefinitionUid(viewDefinitionUid);
    //
    for (final RiskRunProperty property : properties) {
      property.setRiskRun(this);
    }
  }

  public RiskRun(final ViewCycleMetadata cycleMetadata) {
    this(new MarketData(cycleMetadata.getMarketDataSnapshotId()),
        Instant.now(),
        cycleMetadata.getValuationTime(),
        0,
        functional(cycleMetadata.getAllCalculationConfigurationNames()).map(new Function1<String, CalculationConfiguration>() {
          @Override
          public CalculationConfiguration execute(final String configName) {
            return new CalculationConfiguration(configName);
          }
        }).asSet(),
        Sets.<RiskRunProperty>newHashSet(),
        false,
        cycleMetadata.getVersionCorrection(),
        cycleMetadata.getViewDefinitionId(),
        cycleMetadata.getName());
  }

  public Map<String, String> getPropertiesMap() {
    final Map<String, String> returnValue = new HashMap<>();

    for (final RiskRunProperty property : getProperties()) {
      returnValue.put(property.getPropertyKey(), property.getPropertyValue());
    }

    return returnValue;
  }

  public void addProperty(final RiskRunProperty property) {
    _properties.add(property);
  }

  public void addProperty(final String key, final String value) {
    final RiskRunProperty property = new RiskRunProperty();
    property.setRiskRun(this);
    property.setPropertyKey(key);
    property.setPropertyValue(value);
    addProperty(property);
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code RiskRun}.
   * @return the meta-bean, not null
   */
  public static RiskRun.Meta meta() {
    return RiskRun.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(RiskRun.Meta.INSTANCE);
  }

  @Override
  public RiskRun.Meta metaBean() {
    return RiskRun.Meta.INSTANCE;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the id.
   * @return the value of the property
   */
  public long getId() {
    return _id;
  }

  /**
   * Sets the id.
   * @param id  the new value of the property
   */
  public void setId(long id) {
    this._id = id;
  }

  /**
   * Gets the the {@code id} property.
   * @return the property, not null
   */
  public final Property<Long> id() {
    return metaBean().id().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the marketData.
   * @return the value of the property
   */
  public MarketData getMarketData() {
    return _marketData;
  }

  /**
   * Sets the marketData.
   * @param marketData  the new value of the property
   */
  public void setMarketData(MarketData marketData) {
    this._marketData = marketData;
  }

  /**
   * Gets the the {@code marketData} property.
   * @return the property, not null
   */
  public final Property<MarketData> marketData() {
    return metaBean().marketData().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the createInstant.
   * @return the value of the property
   */
  public Instant getCreateInstant() {
    return _createInstant;
  }

  /**
   * Sets the createInstant.
   * @param createInstant  the new value of the property
   */
  public void setCreateInstant(Instant createInstant) {
    this._createInstant = createInstant;
  }

  /**
   * Gets the the {@code createInstant} property.
   * @return the property, not null
   */
  public final Property<Instant> createInstant() {
    return metaBean().createInstant().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the startInstant.
   * @return the value of the property
   */
  public Instant getStartInstant() {
    return _startInstant;
  }

  /**
   * Sets the startInstant.
   * @param startInstant  the new value of the property
   */
  public void setStartInstant(Instant startInstant) {
    this._startInstant = startInstant;
  }

  /**
   * Gets the the {@code startInstant} property.
   * @return the property, not null
   */
  public final Property<Instant> startInstant() {
    return metaBean().startInstant().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the endInstant.
   * @return the value of the property
   */
  public Instant getEndInstant() {
    return _endInstant;
  }

  /**
   * Sets the endInstant.
   * @param endInstant  the new value of the property
   */
  public void setEndInstant(Instant endInstant) {
    this._endInstant = endInstant;
  }

  /**
   * Gets the the {@code endInstant} property.
   * @return the property, not null
   */
  public final Property<Instant> endInstant() {
    return metaBean().endInstant().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the valuationTime.
   * @return the value of the property
   */
  public Instant getValuationTime() {
    return _valuationTime;
  }

  /**
   * Sets the valuationTime.
   * @param valuationTime  the new value of the property
   */
  public void setValuationTime(Instant valuationTime) {
    this._valuationTime = valuationTime;
  }

  /**
   * Gets the the {@code valuationTime} property.
   * @return the property, not null
   */
  public final Property<Instant> valuationTime() {
    return metaBean().valuationTime().createProperty(this);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the numRestarts.
   * @return the value of the property
   */
  public int getNumRestarts() {
    return _numRestarts;
  }

  /**
   * Sets the numRestarts.
   * @param numRestarts  the new value of the property
   */
  public void setNumRestarts(int numRestarts) {
    this._numRestarts = numRestarts;
  }

  /**

projects/web/web-engine/WEB-INF/pages/conventions/json/convention.ftl
{
    "template_data": {
		<#if configJSON??>
      		"configJSON":${configJSON},
		</#if>
		<#if configXML??>
      		"configXML":"${configXML}",
		</#if>
		<#if deleted>
      		"deleted":"${configDoc.versionToInstant}",
		</#if>
      	"name":"${conventionDoc.name}",
      	"type":"${conventionDescription}",
      	"object_id":"${conventionDoc.uniqueId.objectId}",
      	"version_id":"${conventionDoc.uniqueId.version}"
    }
}

projects/web/web-engine/WEB-INF/pages/conventions/json/conventions.ftl
<#escape x as x?html>
{
    "header" : {
        "type":"Conventions",
        <#if searchResult??>
        "pgIdx": ${"${paging.firstItem}"?replace(',','')},
        "pgSze": ${"${paging.pagingSize}"?replace(',','')},
        "pgTtl": ${"${paging.totalItems}"?replace(',','')},
        </#if>
        "dataFields":["id","name"<#if type = ''>,"type"</#if>]
    },
    "data" : [<#if searchResult??>
       <#list searchResult.documents as doc>
           "${doc.uniqueId.objectId}|${doc.convention.name}<#if type = ''>|${doc.convention.class.simpleName}</#if>"<#if doc_has_next>,</#if>
       </#list>
    </#if>]
}
</#escape>

projects/web/web-engine/WEB-INF/pages/conventions/json/conventionversions.ftl
<#escape x as x?html>
{
    "header": {
        "type": "ConventionHistory",
        <#if versionsResult??>
        "pgIdx": ${"${paging.firstItem}"?replace(',','')},
        "pgSze": ${"${paging.pagingSize}"?replace(',','')},
        "pgTtl": ${"${paging.totalItems}"?replace(',','')},
        </#if>
        "object_id": "${convention.uniqueId.objectId}",
        "dataFields": ["version", "name", "validFrom", "validTo", "correctionFrom", "correctionTo"]
    },
    "data": [<#if versionsResult??>
        <#list versionsResult.documents as item>
        "${item.uniqueId.version}|${item.value.name}|${item.versionFromInstant}|${item.versionToInstant}|${item.correctionFromInstant}|${item.correctionToInstant}"<#if item_has_next>,</#if>
        </#list>
     </#if>]
}
</#escape>

projects/web/web-engine/WEB-INF/pages/conventions/json/metadata.ftl
<#escape x as x?html>
{
  "types" : [
    <#list conventionDescriptionMap?keys as key>
      {"value" : "${key}", "name" : "${conventionDescriptionMap[key]}"}<#if key_has_next>,</#if>
    </#list>
  ],
  "groups" : [
    <#list conventionGroups?keys as groupKey>
    {
      "group" : "${groupKey}",
      "types" : [
        <#list conventionGroups[groupKey]?keys as typeKey>
          {"value" : "${typeKey}", "name" : "${conventionGroups[groupKey][typeKey]}"}<#if typeKey_has_next>,</#if>
        </#list>
      ]
    }<#if groupKey_has_next>,</#if>
    </#list>
  ]
}
</#escape>

projects/web/web-engine/WEB-INF/pages/conventions/json/template.ftl
{
    "template_data": {
      <#if template?has_content>"configJSON":${template},</#if>
      "name":"",
      "object_id":"",
      "version_id":"",
      "type":"${type}"
    }
}